# Generated by Django 3.2.4 on 2021-06-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('college', models.CharField(max_length=245)),
                ('dept_name', models.CharField(max_length=245)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
    ]
