# Generated by Django 3.2.4 on 2021-06-09 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210606_2148'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
