# Generated by Django 3.2.4 on 2021-06-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0006_delete_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('type', models.CharField(choices=[('green', 'green'), ('red', 'red')], max_length=245)),
                ('college', models.CharField(max_length=245)),
                ('dept_name', models.CharField(max_length=245)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
