# Generated by Django 3.2.4 on 2021-06-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_alter_certificate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Individual', 'Individual')], max_length=245),
        ),
    ]
