# Generated by Django 3.2.4 on 2021-06-10 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_certificate_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
