# Generated by Django 3.2.4 on 2021-06-10 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_certificate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
