# Generated by Django 3.2.4 on 2021-06-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=245)),
                ('email', models.CharField(max_length=245)),
                ('phone', models.CharField(max_length=245)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('type', models.CharField(choices=[('Student', 'Student'), ('Individual', 'Individual')], max_length=245)),
                ('card', models.CharField(max_length=245)),
                ('dob', models.DateField()),
            ],
        ),
    ]
