# Generated by Django 3.2.4 on 2021-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='card',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(max_length=12),
        ),
    ]
