# Generated by Django 3.2.4 on 2021-06-10 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_person_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate',
        ),
    ]
